export enum ApiEndPoint {
  PREFIX = '/auth',
  SIGNUP = '/signup',
  LOGIN = '/login',
  LOGOUT = '/logout',
  SOCIAL_LOGIN = '/social_login',
  VERIFY_ACCOUNT = '/verify_account/:_id',
  VERIFY_FORGOT_ACCOUNT = '/verify_forgot_account/:_id',
  RESEND_OTP = '/resend_otp',
  GET_VERIFICATION_CODE = '/get_verification_code',
  GET_VERIFIED_USER = '/get_verified_user',
  FORGOT_PASSWORD = '/forgot_password',
  VALIDATE_RESET_PWD_OTP = '/validate_reset_pwd_otp',
  VERIFY_LOGIN_OTP = '/verify_login_otp',
  RESET_PASSWORD = '/reset_password',
  REFRESH = '/refresh',
  ME = '/me',
  DEEPLINK = '/deeplink',
}
export enum ClinicianApiEndPoint {
  PREFIX = '/clinician/auth',
  SIGNUP = '/signup',
  LOGIN = '/login',
  LOGOUT = '/logout',
  SOCIAL_LOGIN = '/social_login',
  VERIFY_ACCOUNT = '/verify_account/:clinicianId',
  RESEND_OTP = '/resend_otp',
  GET_VERIFICATION_CODE = '/get_verification_code',
  FORGOT_PASSWORD = '/forgot_password',
  VALIDATE_RESET_PWD_OTP = '/validate_reset_pwd_otp',
  VERIFY_LOGIN_OTP = '/verify_login_otp',
  RESET_PASSWORD = '/reset_password',
  REFRESH = '/refresh',
  ME = '/me',
  DEEPLINK = '/deeplink',
}

export enum AdminEndPoint {
  PREFIX = '/admin',
  LOGIN = '/login',
  LOGOUT = '/logout',
  FORGOT_PASSWORD = '/forgot_password',
  VALIDATE_RESET_PWD_OTP = '/validate_reset_pwd_otp',
  RESET_PASSWORD = '/reset_password',
  CHANGE_PASSWORD = '/change_password',
  REFRESH_TOKEN = '/refresh_token',
  PROFILE = '/profile',
  RESEND_OTP = '/resend_otp',
  UPDATE_PROFILE = '/profile',
  UPDATE_DEVICE_TOKEN = '/update-device-token',

}
